ALTER TABLE [dbo].[GolfCourse_GroupEvent]
    ADD CONSTRAINT [PK_GolfCourse_GroupEvent] PRIMARY KEY CLUSTERED ([GolfCourse_Event_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

