ALTER TABLE [dbo].[GolfCourse_OpenTeeTime]
    ADD CONSTRAINT [PK_GolfCourse_OpenTeeTime] PRIMARY KEY CLUSTERED ([GolfCourse_OpenTeeTime_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

