ALTER TABLE [dbo].[GolfCourse_Event_ApprovedGolfer]
    ADD CONSTRAINT [PK_GolfCourse_Event_ApprovedGolfer] PRIMARY KEY CLUSTERED ([GolfCourse_Event_ApprovedGolfer_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

