/*ALTER TABLE [dbo].[GolfCourse]
    ADD CONSTRAINT [PK_GolfCourse] PRIMARY KEY CLUSTERED ([GolfCourse_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

