ALTER TABLE [dbo].[GolferPrivateMessage]
    ADD CONSTRAINT [PK_GolferPrivateMessage] PRIMARY KEY CLUSTERED ([GolferPrivateMessageId] DESC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

